Update p3.mdx
GeekCornerGH/docs pull request #8
Opened 2023-02-06 18:49 UTC by sjempotje

2023-02-06 19:01 UTC, GeekCornerGH requested changes
Hmm, fail?

2023-02-06 19:03 UTC, sjempotje commented
yeah it was a test for signing, adding more now 👀

2023-02-07 06:21 UTC, GeekCornerGH requested changes

2023-02-07 06:21 UTC, GeekCornerGH commented on docusaurus.config.js
> +    defaultLocale: 'ru',
```suggestion
    defaultLocale: 'fr',
```

2023-02-07 06:22 UTC, GeekCornerGH approved these changes

2023-02-07 06:24 UTC, merged